server.port: 7002

spring.cloud.function.definition: messageProcessor

spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings.messageProcessor-in-0:
    destination: orders
    group: ordersGroup


spring.cloud.stream.bindings.messageProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.kafka.bindings.messageProcessor-in-0.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092
