springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: rafetefe.composite
  pathsToMatch: /**

api:
  common:
    version: 1.0.0
    title: ecommerce-microservice-docs
    description: sampleDescription

    contact:
      name: rafetefe
      url: https://github.com/rafetefe/

server.port: 7000

app:
  product:
    host: 0.0.0.0
    port: 7001
  order:
    host: 0.0.0.0
    port: 7002
  cart:
    host: 0.0.0.0
    port: 7003

spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings:
    products-out-0:
      destination: products
    orders-out-0:
      destination: orders
    carts-out-0:
      destination: carts

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

---